spring:
  config:
    activate:
      on-profile: secret

auth:
  mode: ${AUTH_MODE}
  jwt:
    secret-key: ${AUTH_JWT_SECRET_KEY}
    grant-type: ${AUTH_JWT_GRANT_TYPE}
  allowed-statuses: ${AUTH_ALLOWED_STATUSES}
  excluded-patterns: ${AUTH_EXCLUDED_PATTERNS}
