spring:
  config:
    activate:
      on-profile: secret

auth:
  jwt:
    grant-type: ${AUTH_JWT_GRANT-TYPE}
    secret-key: ${AUTH_JWT_SECRET-KEY}
    token-type-claim: type
    device-id-claim: deviceId
    authorities-claim: authorities
